refactor: 'package/appimage' github actions (#56)
* refactor: change the OS check

* refactor: use 'curl' instead of 'wget'

* refactor: use 'mktemp' instead of 'uuidgen'

* refactor: add echo outputs

* fix: create output dir

* fix: add dir to environment paths

* fix: correct output package path

diff --git a/package/appimage/pack/action.yml b/package/appimage/pack/action.yml
--- a/package/appimage/pack/action.yml
+++ b/package/appimage/pack/action.yml
@@ -57,22 +57,23 @@ runs:
   using: "composite"
 
   steps:
+
+    - name: Check the operating system
+      if: ${{ runner.os != 'Linux' }}
+      shell: bash
+      run: echo "::error::This action only supports Linux (Now it runs on $RUNNER_OS)."
+
     - name: Check conditions
       shell: bash
       run: |
-        if [ "$RUNNER_OS" != "Linux" ]; then
-          echo "::error::This action only supports Linux (Now it runs on $RUNNER_OS)."
-          exit 1
-        fi
-
         if ( ! command -v "${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE }}" ); then
           echo "::error::'${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE }}' command not found"
-          exit 2
+          exit 1
         fi
 
         if [ ! -d "${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR }}" ]; then
           echo "::error::'${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR }}' directory does not exist"
-          exit 3
+          exit 1
         fi
 
     - name: Pack
@@ -85,20 +86,16 @@ runs:
         output_dir="${{ inputs.package-output-dir }}"
         package_app_dir="${{ inputs.package-app-dir }}"
 
-        here="$(pwd)"
-        tmp_dir="$output_dir/$(uuidgen)"
-
-        echo "Create '$tmp_dir' directory"
-
-        mkdir -p "$tmp_dir"
+        start_dir="$(pwd)"
 
         function clean() {
             echo "Cleaning..."
-            cd "$here"
-            rm -drf "$tmp_dir"
+            cd "$start_dir"
         }
 
         trap clean EXIT
+
+        echo "Prepare environment..."
 
         package_runtime=${{ inputs.package-runtime }}
 
@@ -124,23 +121,27 @@ runs:
         appimagetool_realpath=$(readlink -e "${appimagetool}")
         runtime_realpath=$(readlink -e "${runtime}")
         package_app_dir_realpath=$(readlink -e "${package_app_dir}")
+
+        echo "Prepare directory..."
+
+        mkdir -p "$output_dir"
         output_dir_realpath=$(readlink -e "${output_dir}")
 
+        tmp_dir="$(mktemp -d)"
         cd "$tmp_dir"
 
         echo "Packing..."
 
         echo "$("${appimagetool_realpath}" --runtime-file="${runtime_realpath}" "${package_app_dir_realpath}")"
 
-        cd "$here"
+        cd "$start_dir"
 
-        package=$(find . -path "$tmp_dir/*.AppImage" -print | head -n 1)
+        package=$(find "$tmp_dir" -path "*.AppImage" -print | head -n 1)
         package_name=$(basename -- "$package")
 
         chmod a+x "$package"
 
-        mkdir -p "$output_dir"
-        mv "$package" "$output_dir"
+        mv "$package" "$output_dir_realpath"
 
         echo "AppImage package is '$output_dir/$package_name'"
         echo "appimage-package=$output_dir/$package_name" >> $GITHUB_OUTPUT
