feat: add the 'toolset/file/read' action (#48)
* feat: add the 'toolset/file/read' action

* fix: fix test file

* fix: fix the 'toolset/file/read' action

* fix: fix the 'check-toolset-actions.yml' workflow

* fix: fix test file

* fix: fix the 'check-toolset-actions.yml' workflow

* fix: fix the 'check-toolset-actions.yml' workflow

* fix: fix the 'check-toolset-actions.yml' workflow

diff --git a/.github/workflows/check-toolset-actions.yml b/.github/workflows/check-toolset-actions.yml
--- a/.github/workflows/check-toolset-actions.yml
+++ b/.github/workflows/check-toolset-actions.yml
@@ -71,6 +71,90 @@ jobs:
           exit 1
         fi
 
+    - name: Run 'toolset/file/read' action [.txt]
+      id: read-text-file
+      uses: ./toolset/file/read
+      with:
+        file: '${{ env.test-data-dir }}/file/read/test.txt'
+
+    - name: Run 'toolset/file/read' action [.json]
+      id: read-json-file
+      uses: ./toolset/file/read
+      with:
+        file: '${{ env.test-data-dir }}/file/read/test.json'
+
+    - name: Check 'toolset/file/read' action
+      shell: bash
+      run: | 
+        actual_txt_data="${{ steps.read-text-file.outputs.data }}"
+        expected_txt_data="This is a test file.
+        This is a new line.
+        These are several numbers: 0, 1, 2, 3."
+
+        if [ "$actual_txt_data" != "$expected_txt_data" ]; then
+          echo "::error::The 'toolset/file/read' action failed the tests. The file 'test.txt' is read incorrectly."
+          echo "Differences:"
+          diff <(echo "$actual_txt_data") <(echo "$expected_txt_data")
+          exit 2
+        fi
+
+        actual_itemA0="${{ fromJSON(steps.read-json-file.outputs.data).item-A-0 }}"
+        expected_itemA0="value-A-0"
+        if [ "$actual_itemA0" != "$expected_itemA0" ]; then
+          echo "::error::The 'toolset/file/read' action failed the tests. The 'item-A-0' item is incorrect."
+          echo "Differences:"
+          diff <(echo "$actual_itemA0") <(echo "$expected_itemA0")
+          exit 2
+        fi
+
+        actual_itemA2="${{ fromJSON(steps.read-json-file.outputs.data).item-A-2 }}"
+        expected_itemA2=2
+        if [ "$actual_itemA0" != "$expected_itemA0" ]; then
+          echo "::error::The 'toolset/file/read' action failed the tests. The 'item-A-2' item is incorrect."
+          exit 2
+        fi
+
+        actual_sectionB_itemB0="${{ fromJSON(steps.read-json-file.outputs.data).section-B.item-B-0 }}"
+        expected_sectionB_itemB0="value-B-0"
+        if [ "$actual_sectionB_itemB0" != "$expected_sectionB_itemB0" ]; then
+          echo "::error::The 'toolset/file/read' action failed the tests. The 'section-B.item-B-0' item is incorrect."
+          echo "Differences:"
+          diff <(echo "$actual_sectionB_itemB0") <(echo "$expected_sectionB_itemB0")
+          exit 2
+        fi
+
+        actual_sectionB_itemB2="${{ fromJSON(steps.read-json-file.outputs.data).section-B.item-B-2 }}"
+        expected_sectionB_itemB2=12
+        if [ "$actual_sectionB_itemB2" != "$expected_sectionB_itemB2" ]; then
+          echo "::error::The 'toolset/file/read' action failed the tests. The 'section-B.item-B-2' item is incorrect."
+          exit 2
+        fi
+
+        actual_arrayC_itemC0="${{ fromJSON(steps.read-json-file.outputs.data).array-C[0].item-C-0 }}"
+        expected_arrayC_itemC0="value-C-00"
+        if [ "$actual_arrayC_itemC0" != "$expected_arrayC_itemC0" ]; then
+          echo "::error::The 'toolset/file/read' action failed the tests. The 'array-C[0].item-C-0' item is incorrect."
+          echo "Differences:"
+          diff <(echo "$actual_arrayC_itemC0") <(echo "$expected_arrayC_itemC0")
+          exit 2
+        fi
+
+        actual_arrayC_itemC2="${{ fromJSON(steps.read-json-file.outputs.data).array-C[1].item-C-2 }}"
+        expected_arrayC_itemC2=212
+        if [ "$actual_arrayC_itemC2" != "$expected_arrayC_itemC2" ]; then
+          echo "::error::The 'toolset/file/read' action failed the tests. The 'array-C[1].item-C-2' item is incorrect."
+          exit 2
+        fi
+
+        actual_arrayD="${{ fromJSON(steps.read-json-file.outputs.data).array-D[0] }}"
+        expected_arrayD="value-D-0"
+        if [ "$actual_arrayD" != "$expected_arrayD" ]; then
+          echo "::error::The 'toolset/file/read' action failed the tests. The 'array-D[0]' item is incorrect."
+          echo "Differences:"
+          diff <(echo "$actual_arrayD") <(echo "$expected_arrayD")
+          exit 2
+        fi
+
     - name: Run 'toolset/find-out-version' action
       id: version-number
       uses: ./toolset/find-out-version
@@ -84,42 +168,42 @@ jobs:
         echo "Major: $major"
         if [[ ! $major =~  $regex_number ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'major' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         minor="${{ steps.version-number.outputs.minor }}"
         echo "Minor: $minor"
         if [[ ! $minor =~  $regex_number ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'minor' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         patch="${{ steps.version-number.outputs.patch }}"
         echo "Patch: $patch"
         if [[ ! $patch =~  $regex_number ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'patch' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         build="${{ steps.version-number.outputs.build }}"
         echo "Build: $build"
         if [[ ! $build =~  $regex_number ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'build' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         attempt="${{ steps.version-number.outputs.attempt }}"
         echo "Attempt: $attempt"
         if [[ ! $attempt =~  $regex_number ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'attempt' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         today="${{ steps.version-number.outputs.today }}"
         echo "Today: $today"
         if [[ ! $today =~  $regex_number ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'today' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         regex_hex_number="^[0-9a-fA-F]+$"
@@ -127,7 +211,7 @@ jobs:
         echo "Git hash: $githash"
         if [[ ! $githash =~  $regex_hex_number ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'githash' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         regex_suffix="^[a-zA-Z0-9\.-]?$"
@@ -135,7 +219,7 @@ jobs:
         echo "Suffix: $suffix"
         if [[ ! $suffix =~  $regex_suffix ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'suffix' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         preset_build_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"
@@ -143,7 +227,7 @@ jobs:
         echo "Preset Build version: $preset_build"
         if [[ ! $preset_build =~ $preset_build_regex ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-build' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         preset_suffix_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?$"
@@ -151,7 +235,7 @@ jobs:
         echo "Preset Suffix version: $preset_suffix"
         if [[ ! $preset_suffix =~ $preset_suffix_regex ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-suffix' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         preset_semantic_1_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$"
@@ -159,7 +243,7 @@ jobs:
         echo "Preset Semantic version 1.0: $preset_semantic_1"
         if [[ ! $preset_semantic_1 =~ $preset_semantic_1_regex ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-1' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         preset_semantic_2_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?(\+[a-zA-Z0-9\.-]+)?$"
@@ -167,7 +251,7 @@ jobs:
         echo "Preset Semantic version 2.0: $preset_semantic_2"
         if [[ ! $preset_semantic_2 =~ $preset_semantic_2_regex ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-2' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         preset_build_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\+[0-9a-fA-F]+$"
@@ -175,7 +259,7 @@ jobs:
         echo "Preset Build version with githash: $preset_build_githash"
         if [[ ! $preset_build_githash =~ $preset_build_githash_regex ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-build-githash' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         preset_suffix_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?\+[0-9a-fA-F]+$"
@@ -183,7 +267,7 @@ jobs:
         echo "Preset Suffix version with githash: $preset_suffix_githash"
         if [[ ! $preset_suffix_githash =~ $preset_suffix_githash_regex ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-suffix-githash' output is incorrect."
-          exit 2
+          exit 3
         fi
 
         preset_semantic_2_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?\+([a-zA-Z0-9\.-]+\.)?[0-9a-fA-F]+$"
@@ -191,6 +275,5 @@ jobs:
         echo "Preset Semantic version 2.0 with githash: $preset_semantic_2_githash"
         if [[ ! $preset_semantic_2_githash =~ $preset_semantic_2_githash_regex ]]; then
           echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-2-githash' output is incorrect."
-          exit 2
+          exit 3
         fi
-
