feat: add test for the 'toolset/select-configuration' action

diff --git a/.github/workflows/check-toolset-select-config-actions.yml b/.github/workflows/check-toolset-select-config-actions.yml
--- a/.github/workflows/check-toolset-select-config-actions.yml
+++ b/.github/workflows/check-toolset-select-config-actions.yml
@@ -41,6 +41,10 @@ jobs:
 
     runs-on: ${{ matrix.os }}
 
+    outputs:
+      matrix: ${{ steps.select-config-from-json-one-output.outputs.matrix }}
+      os: ${{ matrix.os }}
+
     env:
       test-data-dir: './toolset/.tests/select-configuration'
       json: '[{"keywords":["A","B"],"option":"value-a"},{"keywords":["A","C"],"option":"value-b"},{"keywords":["C","B"],"option":"value-c"}]'
@@ -168,6 +172,26 @@ jobs:
       run: | 
         actual_option="${{ fromJson(steps.select-config-from-file.outputs.config-json)[0].option }}"
         expected_option="value-c"
+
+        if [ "$actual_option" != "$expected_option" ]; then
+          echo "::error::The 'toolset/select-configuration' action failed the tests. Configuration option is '$actual_option' but expected '$expected_option'."
+          exit 1
+        fi
+
+  check-matrix:
+
+    needs: checks
+
+    runs-on: ${{ needs.checks.outputs.os }}
+    strategy:
+      matrix: ${{ fromJson(needs.checks.outputs.matrix) }}
+
+    steps:
+    - name: Check 'toolset/select-configuration [matrix]' action
+      shell: bash
+      run: | 
+        actual_option="${{ matrix.option }}"
+        expected_option="value-a"
 
         if [ "$actual_option" != "$expected_option" ]; then
           echo "::error::The 'toolset/select-configuration' action failed the tests. Configuration option is '$actual_option' but expected '$expected_option'."
