feat: fix the 'toolset/select-configuration' action

diff --git a/.github/workflows/check-toolset-select-config-actions.yml b/.github/workflows/check-toolset-select-config-actions.yml
--- a/.github/workflows/check-toolset-select-config-actions.yml
+++ b/.github/workflows/check-toolset-select-config-actions.yml
@@ -90,7 +90,15 @@ jobs:
     - name: Check 'toolset/select-configuration [json]' action
       shell: bash
       run: | 
-        actual_option="${{ fromJson(steps.select-config-from-json-one-output.outputs.config-json).option }}"
+        actual_length=$(echo '${{ steps.select-config-from-json-one-output.outputs.config-json }}' | jq '. | length')  
+        expected_length=1
+
+        if [ "$actual_length" != "$expected_length" ]; then
+          echo "::error::The 'toolset/select-configuration' action failed the tests. Number of configurations is '$actual_length' but expected '$expected_length'."
+          exit 1
+        fi
+
+        actual_option="${{ fromJson(steps.select-config-from-json-one-output.outputs.config-json)[0].option }}"
         expected_option="value-a"
 
         if [ "$actual_option" != "$expected_option" ]; then
@@ -98,7 +106,7 @@ jobs:
           exit 1
         fi
 
-        actual_length="${{ fromJson(steps.select-config-from-json-several-output.outputs.config-json).length }}"
+        actual_length=$(echo '${{ steps.select-config-from-json-several-output.outputs.config-json }}' | jq '. | length')  
         expected_length=2
 
         if [ "$actual_length" != "$expected_length" ]; then
@@ -114,7 +122,7 @@ jobs:
           exit 1
         fi
 
-        actual_length="${{ fromJson(steps.select-config-from-json-none-output.outputs.config-json).length }}"
+        actual_length=$(echo '${{ steps.select-config-from-json-none-output.outputs.config-json }}' | jq '. | length')  
         expected_length=0
 
         if [ "$actual_length" != "$expected_length" ]; then
@@ -122,7 +130,7 @@ jobs:
           exit 1
         fi
 
-        actual_length="${{ fromJson(steps.select-config-from-json-double-key.outputs.config-json).length }}"
+        actual_length=$(echo '${{ steps.select-config-from-json-double-key.outputs.config-json }}' | jq '. | length')  
         expected_length=2
 
         if [ "$actual_length" != "$expected_length" ]; then
@@ -138,7 +146,7 @@ jobs:
           exit 1
         fi
 
-        actual_keyword="${{ fromJson(steps.select-config-from-json-with-keywords.outputs.config-json).keywords[0] }}"
+        actual_keyword="${{ fromJson(steps.select-config-from-json-with-keywords.outputs.config-json)[0].keywords[0] }}"
         expected_keyword="C"
 
         if [ "$actual_keyword" != "$expected_keyword" ]; then
@@ -158,7 +166,7 @@ jobs:
     - name: Check 'toolset/select-configuration [json-file]' action
       shell: bash
       run: | 
-        actual_option="${{ fromJson(steps.select-config-from-file.outputs.config-json).option }}"
+        actual_option="${{ fromJson(steps.select-config-from-file.outputs.config-json)[0].option }}"
         expected_option="value-c"
 
         if [ "$actual_option" != "$expected_option" ]; then
