fix: correct the syntax of yaml files

diff --git a/.github/workflows/check-package-appimage-action.yml b/.github/workflows/check-package-appimage-action.yml
--- a/.github/workflows/check-package-appimage-action.yml
+++ b/.github/workflows/check-package-appimage-action.yml
@@ -16,9 +16,11 @@
 #                                                                              #
 ################################################################################
 
+---
+
 name: Check the 'package/appimage' Action
 
-on:
+on: # yamllint disable-line rule:truthy
   workflow_dispatch:
   workflow_call:
 
@@ -28,55 +30,55 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
-      with:
-        fetch-depth: 0
-        submodules: recursive
+      - name: Checkout
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+        with:
+          fetch-depth: 0
+          submodules: recursive
 
-    - name: Run 'package/appimage/setup-appimagetool' action
-      id: setup-appimagetool
-      uses: ./package/appimage/setup-appimagetool
+      - name: Run 'package/appimage/setup-appimagetool' action
+        id: setup-appimagetool
+        uses: ./package/appimage/setup-appimagetool
 
-    - name: Test 'package/appimage/setup-appimagetool' action
-      shell: bash
-      run: |
+      - name: Test 'package/appimage/setup-appimagetool' action
+        shell: bash
+        run: |
 
-        if ( ! command -v "${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE }}" ); then
-          echo "::error::The 'package/appimage/setup-appimagetool' action failed the tests. env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE is '${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE }}'. The command not found."
-          exit 1
-        elif [ ! -d "${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR }}" ]; then
-          echo "::error::The 'package/appimage/setup-appimagetool' action failed the tests. env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR is '${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR }}'. The directory does not exist."
-          exit 1
-        fi
+          if ( ! command -v "${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE }}" ); then
+            echo "::error::The 'package/appimage/setup-appimagetool' action failed the tests. env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE is '${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE }}'. The command not found."
+            exit 1
+          elif [ ! -d "${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR }}" ]; then
+            echo "::error::The 'package/appimage/setup-appimagetool' action failed the tests. env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR is '${{ env.FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR }}'. The directory does not exist."
+            exit 1
+          fi
 
-    - name: Prepare-Run 'package/appimage/pack' action  
-      shell: bash
-      run: |
-        bash "./package/appimage/.test/prepare-Test.AppDir.sh"
+      - name: Prepare-Run 'package/appimage/pack' action
+        shell: bash
+        run: |
+          bash "./package/appimage/.test/prepare-Test.AppDir.sh"
 
-    - name: Run './package/appimage/pack' action with 'aarch64'
-      uses: ./package/appimage/pack
-      with:
-        package-runtime: 'aarch64'
-        package-output-dir: './.output'
-        package-app-dir: './package/appimage/.test/Test.AppDir'
+      - name: Run './package/appimage/pack' action with 'aarch64'
+        uses: ./package/appimage/pack
+        with:
+          package-runtime: 'aarch64'
+          package-output-dir: './.output'
+          package-app-dir: './package/appimage/.test/Test.AppDir'
 
-    - name: Run './package/appimage/pack' action with 'x86_64'
-      id: pack-appimage
-      uses: ./package/appimage/pack
-      with:
-        package-runtime: 'x86_64'
-        package-output-dir: './.output'
-        package-app-dir: './package/appimage/.test/Test.AppDir'
+      - name: Run './package/appimage/pack' action with 'x86_64'
+        id: pack-appimage
+        uses: ./package/appimage/pack
+        with:
+          package-runtime: 'x86_64'
+          package-output-dir: './.output'
+          package-app-dir: './package/appimage/.test/Test.AppDir'
 
-    - name: Test './package/appimage/pack' action with 'x86_64'
-      shell: bash
-      run: |
-        package=${{ steps.pack-appimage.outputs.package }}
+      - name: Test './package/appimage/pack' action with 'x86_64'
+        shell: bash
+        run: |
+          package=${{ steps.pack-appimage.outputs.package }}
 
-        result=$("$package")
-        if [ "$result" != "Hello AppImage" ]; then
-          echo "::error::The 'package/appimage/pack' action failed the tests. The package '$package' is incorrect."
-          exit 1
-        fi
+          result=$("$package")
+          if [ "$result" != "Hello AppImage" ]; then
+            echo "::error::The 'package/appimage/pack' action failed the tests. The package '$package' is incorrect."
+            exit 1
+          fi
diff --git a/.github/workflows/check-package-nuget-action.yml b/.github/workflows/check-package-nuget-action.yml
--- a/.github/workflows/check-package-nuget-action.yml
+++ b/.github/workflows/check-package-nuget-action.yml
@@ -16,9 +16,11 @@
 #                                                                              #
 ################################################################################
 
+---
+
 name: Check the 'package/nuget' Action
 
-on:
+on: # yamllint disable-line rule:truthy
   workflow_dispatch:
   workflow_call:
 
@@ -31,37 +33,37 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
-      with:
-        fetch-depth: 0
+      - name: Checkout
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+        with:
+          fetch-depth: 0
 
-    - name: Install dotnet
-      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
-      with:
-        dotnet-version: 8.x
+      - name: Install dotnet
+        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
+        with:
+          dotnet-version: 8.x
 
-    - name: Run 'package/nuget/pack' action
-      uses: ./package/nuget/pack
-      with:
-        project: ./package/nuget/.test/Nuget/Nuget.csproj
-        configuration: Release
-        package-version: '1.0.0'
-        push-to-nuget: false
-        push-to-github: false
-        upload-artifact: false
+      - name: Run 'package/nuget/pack' action
+        uses: ./package/nuget/pack
+        with:
+          project: ./package/nuget/.test/Nuget/Nuget.csproj
+          configuration: Release
+          package-version: '1.0.0'
+          push-to-nuget: false
+          push-to-github: false
+          upload-artifact: false
 
-    - name: Check the result of the 'package/nuget/pack' action
-      shell: bash
-      run: |
-        nupkg="${{ env.package-root }}/Finebits.Nuget.1.0.0.nupkg"
-        if [ ! -f "$nupkg" ]; then
-          echo "::error::The 'package/nuget/pack' action failed the tests. File 'Finebits.Nuget.1.0.0.nupkg' not found"
-          exit 1
-        fi
+      - name: Check the result of the 'package/nuget/pack' action
+        shell: bash
+        run: |
+          nupkg="${{ env.package-root }}/Finebits.Nuget.1.0.0.nupkg"
+          if [ ! -f "$nupkg" ]; then
+            echo "::error::The 'package/nuget/pack' action failed the tests. File 'Finebits.Nuget.1.0.0.nupkg' not found"
+            exit 1
+          fi
 
-        snupkg="${{ env.package-root }}/Finebits.Nuget.1.0.0.snupkg"
-        if [ ! -f "$snupkg" ]; then
-          echo "::error::The 'package/nuget/pack' action failed the tests. File 'Finebits.Nuget.1.0.0.snupkg' not found"
-          exit 1
-        fi
+          snupkg="${{ env.package-root }}/Finebits.Nuget.1.0.0.snupkg"
+          if [ ! -f "$snupkg" ]; then
+            echo "::error::The 'package/nuget/pack' action failed the tests. File 'Finebits.Nuget.1.0.0.snupkg' not found"
+            exit 1
+          fi
