feat: add 'yamllint' check (#52)
* feat: add 'yamllint' check

* fix: correct the syntax of yaml files

* fix: correct the syntax of yaml files

diff --git a/.github/workflows/check-toolset-file-replace-text-action.yml b/.github/workflows/check-toolset-file-replace-text-action.yml
--- a/.github/workflows/check-toolset-file-replace-text-action.yml
+++ b/.github/workflows/check-toolset-file-replace-text-action.yml
@@ -16,9 +16,11 @@
 #                                                                              #
 ################################################################################
 
+---
+
 name: Check the 'toolset/file/replace-text' Action
 
-on:
+on: # yamllint disable-line rule:truthy
   workflow_dispatch:
   workflow_call:
 
@@ -33,28 +35,28 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
-      with:
-        fetch-depth: 0
+      - name: Checkout
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+        with:
+          fetch-depth: 0
 
-    - name: Run 'toolset/file/replace-text' action
-      uses: ./toolset/file/replace-text
-      with:
-        file: '${{ env.test-data-dir }}/test-file.txt'
-        find-what: "<placeholder>"
-        replace-with: "new value"
+      - name: Run 'toolset/file/replace-text' action
+        uses: ./toolset/file/replace-text
+        with:
+          file: '${{ env.test-data-dir }}/test-file.txt'
+          find-what: "<placeholder>"
+          replace-with: "new value"
 
-    - name: Check 'toolset/file/replace-text' action
-      shell: bash
-      run: | 
-        actual_file="${{ env.test-data-dir }}/test-file.txt"
-        expected_file="${{ env.test-data-dir }}/expected-file.txt"
-        if (cmp -s "$actual_file" "$expected_file"); then
-          echo "The 'toolset/file/replace-text' action passed the tests"
-        else
-          echo "::error::The 'toolset/file/replace-text' action failed the tests"
-          echo "Differences:"
-          diff "$actual_file" "$expected_file"
-          exit 1
-        fi
+      - name: Check 'toolset/file/replace-text' action
+        shell: bash
+        run: |
+          actual_file="${{ env.test-data-dir }}/test-file.txt"
+          expected_file="${{ env.test-data-dir }}/expected-file.txt"
+          if (cmp -s "$actual_file" "$expected_file"); then
+            echo "The 'toolset/file/replace-text' action passed the tests"
+          else
+            echo "::error::The 'toolset/file/replace-text' action failed the tests"
+            echo "Differences:"
+            diff "$actual_file" "$expected_file"
+            exit 1
+          fi
diff --git a/.github/workflows/check-toolset-version-action.yml b/.github/workflows/check-toolset-version-action.yml
--- a/.github/workflows/check-toolset-version-action.yml
+++ b/.github/workflows/check-toolset-version-action.yml
@@ -16,9 +16,11 @@
 #                                                                              #
 ################################################################################
 
+---
+
 name: Check the 'toolset/find-out-version' Action
 
-on:
+on: # yamllint disable-line rule:truthy
   workflow_dispatch:
   workflow_call:
 
@@ -31,130 +33,130 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
-      with:
-        fetch-depth: 0
+      - name: Checkout
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+        with:
+          fetch-depth: 0
 
-    - name: Run 'toolset/find-out-version' action
-      id: version-number
-      uses: ./toolset/find-out-version
+      - name: Run 'toolset/find-out-version' action
+        id: version-number
+        uses: ./toolset/find-out-version
 
-    - name: Check 'toolset/find-out-version' action
-      shell: bash
-      run: |
-        regex_number="^[0-9]+$"
+      - name: Check 'toolset/find-out-version' action
+        shell: bash
+        run: |
+          regex_number="^[0-9]+$"
 
-        major="${{ steps.version-number.outputs.major }}"
-        echo "Major: $major"
-        if [[ ! $major =~  $regex_number ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'major' output is incorrect."
-          exit 1
-        fi
+          major="${{ steps.version-number.outputs.major }}"
+          echo "Major: $major"
+          if [[ ! $major =~  $regex_number ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'major' output is incorrect."
+            exit 1
+          fi
 
-        minor="${{ steps.version-number.outputs.minor }}"
-        echo "Minor: $minor"
-        if [[ ! $minor =~  $regex_number ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'minor' output is incorrect."
-          exit 1
-        fi
+          minor="${{ steps.version-number.outputs.minor }}"
+          echo "Minor: $minor"
+          if [[ ! $minor =~  $regex_number ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'minor' output is incorrect."
+            exit 1
+          fi
 
-        patch="${{ steps.version-number.outputs.patch }}"
-        echo "Patch: $patch"
-        if [[ ! $patch =~  $regex_number ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'patch' output is incorrect."
-          exit 1
-        fi
+          patch="${{ steps.version-number.outputs.patch }}"
+          echo "Patch: $patch"
+          if [[ ! $patch =~  $regex_number ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'patch' output is incorrect."
+            exit 1
+          fi
 
-        build="${{ steps.version-number.outputs.build }}"
-        echo "Build: $build"
-        if [[ ! $build =~  $regex_number ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'build' output is incorrect."
-          exit 1
-        fi
+          build="${{ steps.version-number.outputs.build }}"
+          echo "Build: $build"
+          if [[ ! $build =~  $regex_number ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'build' output is incorrect."
+            exit 1
+          fi
 
-        attempt="${{ steps.version-number.outputs.attempt }}"
-        echo "Attempt: $attempt"
-        if [[ ! $attempt =~  $regex_number ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'attempt' output is incorrect."
-          exit 1
-        fi
+          attempt="${{ steps.version-number.outputs.attempt }}"
+          echo "Attempt: $attempt"
+          if [[ ! $attempt =~  $regex_number ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'attempt' output is incorrect."
+            exit 1
+          fi
 
-        today="${{ steps.version-number.outputs.today }}"
-        echo "Today: $today"
-        if [[ ! $today =~  $regex_number ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'today' output is incorrect."
-          exit 1
-        fi
+          today="${{ steps.version-number.outputs.today }}"
+          echo "Today: $today"
+          if [[ ! $today =~  $regex_number ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'today' output is incorrect."
+            exit 1
+          fi
 
-        regex_hex_number="^[0-9a-fA-F]+$"
-        githash="${{ steps.version-number.outputs.githash }}"
-        echo "Git hash: $githash"
-        if [[ ! $githash =~  $regex_hex_number ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'githash' output is incorrect."
-          exit 1
-        fi
+          regex_hex_number="^[0-9a-fA-F]+$"
+          githash="${{ steps.version-number.outputs.githash }}"
+          echo "Git hash: $githash"
+          if [[ ! $githash =~  $regex_hex_number ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'githash' output is incorrect."
+            exit 1
+          fi
 
-        regex_suffix="^[a-zA-Z0-9\.-]?$"
-        suffix="${{ steps.version-number.outputs.suffix }}"
-        echo "Suffix: $suffix"
-        if [[ ! $suffix =~  $regex_suffix ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'suffix' output is incorrect."
-          exit 1
-        fi
+          regex_suffix="^[a-zA-Z0-9\.-]?$"
+          suffix="${{ steps.version-number.outputs.suffix }}"
+          echo "Suffix: $suffix"
+          if [[ ! $suffix =~  $regex_suffix ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'suffix' output is incorrect."
+            exit 1
+          fi
 
-        preset_build_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"
-        preset_build="${{ steps.version-number.outputs.preset-build }}"
-        echo "Preset Build version: $preset_build"
-        if [[ ! $preset_build =~ $preset_build_regex ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-build' output is incorrect."
-          exit 1
-        fi
+          preset_build_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"
+          preset_build="${{ steps.version-number.outputs.preset-build }}"
+          echo "Preset Build version: $preset_build"
+          if [[ ! $preset_build =~ $preset_build_regex ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-build' output is incorrect."
+            exit 1
+          fi
 
-        preset_suffix_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?$"
-        preset_suffix="${{ steps.version-number.outputs.preset-suffix }}"
-        echo "Preset Suffix version: $preset_suffix"
-        if [[ ! $preset_suffix =~ $preset_suffix_regex ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-suffix' output is incorrect."
-          exit 1
-        fi
+          preset_suffix_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?$"
+          preset_suffix="${{ steps.version-number.outputs.preset-suffix }}"
+          echo "Preset Suffix version: $preset_suffix"
+          if [[ ! $preset_suffix =~ $preset_suffix_regex ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-suffix' output is incorrect."
+            exit 1
+          fi
 
-        preset_semantic_1_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$"
-        preset_semantic_1="${{ steps.version-number.outputs.preset-semantic-1 }}"
-        echo "Preset Semantic version 1.0: $preset_semantic_1"
-        if [[ ! $preset_semantic_1 =~ $preset_semantic_1_regex ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-1' output is incorrect."
-          exit 1
-        fi
+          preset_semantic_1_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$"
+          preset_semantic_1="${{ steps.version-number.outputs.preset-semantic-1 }}"
+          echo "Preset Semantic version 1.0: $preset_semantic_1"
+          if [[ ! $preset_semantic_1 =~ $preset_semantic_1_regex ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-1' output is incorrect."
+            exit 1
+          fi
 
-        preset_semantic_2_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?(\+[a-zA-Z0-9\.-]+)?$"
-        preset_semantic_2="${{ steps.version-number.outputs.preset-semantic-2 }}"
-        echo "Preset Semantic version 2.0: $preset_semantic_2"
-        if [[ ! $preset_semantic_2 =~ $preset_semantic_2_regex ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-2' output is incorrect."
-          exit 1
-        fi
+          preset_semantic_2_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?(\+[a-zA-Z0-9\.-]+)?$"
+          preset_semantic_2="${{ steps.version-number.outputs.preset-semantic-2 }}"
+          echo "Preset Semantic version 2.0: $preset_semantic_2"
+          if [[ ! $preset_semantic_2 =~ $preset_semantic_2_regex ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-2' output is incorrect."
+            exit 1
+          fi
 
-        preset_build_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\+[0-9a-fA-F]+$"
-        preset_build_githash="${{ steps.version-number.outputs.preset-build-githash }}"
-        echo "Preset Build version with githash: $preset_build_githash"
-        if [[ ! $preset_build_githash =~ $preset_build_githash_regex ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-build-githash' output is incorrect."
-          exit 1
-        fi
+          preset_build_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\+[0-9a-fA-F]+$"
+          preset_build_githash="${{ steps.version-number.outputs.preset-build-githash }}"
+          echo "Preset Build version with githash: $preset_build_githash"
+          if [[ ! $preset_build_githash =~ $preset_build_githash_regex ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-build-githash' output is incorrect."
+            exit 1
+          fi
 
-        preset_suffix_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?\+[0-9a-fA-F]+$"
-        preset_suffix_githash="${{ steps.version-number.outputs.preset-suffix-githash }}"
-        echo "Preset Suffix version with githash: $preset_suffix_githash"
-        if [[ ! $preset_suffix_githash =~ $preset_suffix_githash_regex ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-suffix-githash' output is incorrect."
-          exit 1
-        fi
+          preset_suffix_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?\+[0-9a-fA-F]+$"
+          preset_suffix_githash="${{ steps.version-number.outputs.preset-suffix-githash }}"
+          echo "Preset Suffix version with githash: $preset_suffix_githash"
+          if [[ ! $preset_suffix_githash =~ $preset_suffix_githash_regex ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-suffix-githash' output is incorrect."
+            exit 1
+          fi
 
-        preset_semantic_2_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?\+([a-zA-Z0-9\.-]+\.)?[0-9a-fA-F]+$"
-        preset_semantic_2_githash="${{ steps.version-number.outputs.preset-semantic-2-githash }}"
-        echo "Preset Semantic version 2.0 with githash: $preset_semantic_2_githash"
-        if [[ ! $preset_semantic_2_githash =~ $preset_semantic_2_githash_regex ]]; then
-          echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-2-githash' output is incorrect."
-          exit 1
-        fi
+          preset_semantic_2_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?\+([a-zA-Z0-9\.-]+\.)?[0-9a-fA-F]+$"
+          preset_semantic_2_githash="${{ steps.version-number.outputs.preset-semantic-2-githash }}"
+          echo "Preset Semantic version 2.0 with githash: $preset_semantic_2_githash"
+          if [[ ! $preset_semantic_2_githash =~ $preset_semantic_2_githash_regex ]]; then
+            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-2-githash' output is incorrect."
+            exit 1
+          fi
